import React, { useState } from 'react';
import { Coffee, Car, ShoppingBag, Utensils, Zap, TrendingUp, Sparkles } from 'lucide-react';

export default function OpportunityCost({ navigate }) {
  const presets = [
    { id: 'coffee', label: '매일 프랜차이즈 커피 (월 15만)', monthly: 15, icon: Coffee },
    { id: 'delivery', label: '주말 배달음식 & 술자리 (월 30만)', monthly: 30, icon: Utensils },
    { id: 'shopping', label: '월 1회 명품/패션 쇼핑 (월 50만)', monthly: 50, icon: ShoppingBag },
    { id: 'car', label: '중대형 차량 할부 및 유지비 (월 80만)', monthly: 80, icon: Car },
    { id: 'custom', label: '직접 입력', monthly: 20, icon: Zap }
  ];

  const [selectedPreset, setSelectedPreset] = useState('coffee');
  const [monthlyExpense, setMonthlyExpense] = useState(15); // 만원
  const [years, setYears] = useState(20);
  const [cagr, setCagr] = useState(10); // % (예: 미국 배당성장/지수성장 ETF 평균)
  const [dividendYield, setDividendYield] = useState(3.5); // %

  const handleSelectPreset = (p) => {
    setSelectedPreset(p.id);
    if (p.id !== 'custom') {
      setMonthlyExpense(p.monthly);
    }
  };

  // Compounding math:
  // Total spent without investing: monthlyExpense * 12 * years
  const totalSpent = monthlyExpense * 12 * years;

  // Monthly compounding rate:
  const monthlyRate = (cagr / 100) / 12;
  const totalMonths = years * 12;
  const futureAsset = Math.round(
    monthlyExpense * ((Math.pow(1 + monthlyRate, totalMonths) - 1) / monthlyRate)
  );

  // Future annual and monthly dividend income generated by this asset:
  const annualDividend = Math.round(futureAsset * (dividendYield / 100));
  const monthlyDividend = Math.round(annualDividend / 12);

  const formatMoney = (val) => {
    if (val >= 10000) {
      const eok = Math.floor(val / 10000);
      const rem = Math.round(val % 10000);
      return rem > 0 ? `${eok}억 ${rem.toLocaleString()}만원` : `${eok}억원`;
    }
    return `${Math.round(val).toLocaleString()}만원`;
  };

  return (
    <div className="page-shell py-8 sm:py-12 flex-1">
      <div className="max-w-3xl">
        <div className="flex items-center gap-2 text-xs font-bold text-[var(--accent-strong)] uppercase tracking-wider">
          <TrendingUp className="w-4 h-4" />
          <span>기회비용 계산기</span>
        </div>
        <h1 className="mt-1 text-2xl sm:text-4xl font-extrabold tracking-tight text-[var(--foreground)]">
          "소비 대신 ETF에 투자했다면?"
        </h1>
        <p className="mt-2 text-sm sm:text-base text-[var(--muted-foreground)] leading-relaxed">
          일상에서 무심코 지출하는 작은 소비가 10년, 20년 동안 복리로 불어났을 때 어떤 자산과 평생 배당금이 되는지 확인해보세요.
        </p>
      </div>

      <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_1.4fr]">
        {/* Presets & Controls */}
        <div className="rounded-3xl border border-[var(--line)] bg-white p-5 sm:p-7 shadow-sm space-y-6">
          <h2 className="text-base font-bold text-[var(--foreground)]">소비 항목 선택</h2>

          <div className="grid gap-2.5">
            {presets.map((p) => {
              const Icon = p.icon;
              const isSelected = selectedPreset === p.id;
              return (
                <button
                  key={p.id}
                  type="button"
                  onClick={() => handleSelectPreset(p)}
                  className={`flex items-center justify-between p-3.5 rounded-2xl border text-left transition ${
                    isSelected
                      ? 'border-[var(--accent)] bg-[var(--accent-soft)]/50 text-[var(--accent-strong)] font-bold'
                      : 'border-slate-200 bg-white hover:bg-slate-50 text-[var(--foreground)]'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <span className={`p-2 rounded-xl ${isSelected ? 'bg-[var(--accent)] text-white' : 'bg-slate-100 text-slate-600'}`}>
                      <Icon className="w-4 h-4" />
                    </span>
                    <span className="text-xs sm:text-sm">{p.label}</span>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Amount Slider */}
          <div>
            <div className="flex justify-between text-xs font-bold">
              <span className="text-[var(--muted-foreground)]">월 소비 금액</span>
              <span className="font-mono text-[var(--accent-strong)]">{monthlyExpense}만원/월</span>
            </div>
            <input
              type="range"
              min="5"
              max="200"
              step="5"
              value={monthlyExpense}
              onChange={(e) => {
                setMonthlyExpense(Number(e.target.value));
                setSelectedPreset('custom');
              }}
              className="fire-range mt-2 w-full"
            />
          </div>

          {/* Duration Slider */}
          <div>
            <div className="flex justify-between text-xs font-bold">
              <span className="text-[var(--muted-foreground)]">투자 지속 기간</span>
              <span className="font-mono text-[var(--foreground)]">{years}년</span>
            </div>
            <input
              type="range"
              min="5"
              max="40"
              step="1"
              value={years}
              onChange={(e) => setYears(Number(e.target.value))}
              className="fire-range mt-2 w-full"
            />
            <div className="mt-1 flex justify-between text-[10px] text-[var(--muted-foreground)]">
              <span>5년</span>
              <span>20년</span>
              <span>40년</span>
            </div>
          </div>

          {/* Expected Return */}
          <div className="grid grid-cols-2 gap-3 pt-3 border-t">
            <div>
              <label className="block text-[11px] font-semibold text-[var(--muted-foreground)]">ETF 연 기대수익률</label>
              <div className="mt-1 flex items-center rounded-xl border border-[var(--line)] px-2.5 py-1.5 bg-slate-50">
                <input
                  type="number"
                  value={cagr}
                  onChange={(e) => setCagr(Number(e.target.value))}
                  className="w-full bg-transparent font-mono font-bold text-xs sm:text-sm outline-none"
                />
                <span className="text-xs text-[var(--muted-foreground)]">%</span>
              </div>
            </div>
            <div>
              <label className="block text-[11px] font-semibold text-[var(--muted-foreground)]">은퇴 시 배당률</label>
              <div className="mt-1 flex items-center rounded-xl border border-[var(--line)] px-2.5 py-1.5 bg-slate-50">
                <input
                  type="number"
                  step="0.1"
                  value={dividendYield}
                  onChange={(e) => setDividendYield(Number(e.target.value))}
                  className="w-full bg-transparent font-mono font-bold text-xs sm:text-sm outline-none"
                />
                <span className="text-xs text-[var(--muted-foreground)]">%</span>
              </div>
            </div>
          </div>
        </div>

        {/* Results Banner & Comparison */}
        <div className="space-y-6">
          <div className="rounded-3xl border border-[var(--line)] bg-[var(--navy)] text-white p-6 sm:p-8 shadow-xl relative overflow-hidden">
            <div className="relative z-10">
              <span className="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-[var(--fire-amber-soft)]">
                <Sparkles className="w-3.5 h-3.5" /> 복리의 마법
              </span>

              <h3 className="mt-4 text-xl sm:text-2xl font-bold">
                {years}년 뒤 당신이 가질 수 있는 자산
              </h3>

              <div className="mt-4 text-3xl sm:text-5xl font-black text-[var(--fire-amber)] font-mono">
                {formatMoney(futureAsset)}
              </div>

              <div className="mt-6 grid grid-cols-2 gap-4 pt-6 border-t border-white/15">
                <div>
                  <p className="text-xs text-white/60">그냥 썼다면 사라진 원금</p>
                  <p className="numeric mt-1 text-lg sm:text-xl font-bold text-white/80">
                    {formatMoney(totalSpent)}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-emerald-300">평생 나오는 월 배당금</p>
                  <p className="numeric mt-1 text-lg sm:text-xl font-bold text-emerald-300">
                    월 {monthlyDividend.toLocaleString()}만원
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Breakdown cards */}
          <div className="grid grid-cols-2 gap-3">
            <div className="rounded-2xl border border-[var(--line)] bg-white p-4 shadow-sm">
              <span className="text-xs text-[var(--muted-foreground)]">수익 배수</span>
              <p className="numeric mt-1 text-xl sm:text-2xl font-bold text-[var(--accent-strong)]">
                {(futureAsset / (totalSpent || 1)).toFixed(1)}배
              </p>
              <p className="mt-1 text-[11px] text-[var(--muted-foreground)]">원금 대비 증가율</p>
            </div>
            <div className="rounded-2xl border border-[var(--line)] bg-white p-4 shadow-sm">
              <span className="text-xs text-[var(--muted-foreground)]">순 복리 수익금</span>
              <p className="numeric mt-1 text-xl sm:text-2xl font-bold text-emerald-600">
                +{formatMoney(Math.max(0, futureAsset - totalSpent))}
              </p>
              <p className="mt-1 text-[11px] text-[var(--muted-foreground)]">이자 및 시세차익</p>
            </div>
          </div>

          <div className="p-5 rounded-3xl border border-slate-200 bg-slate-50 text-xs sm:text-sm text-slate-700 leading-relaxed">
            💡 <strong>인사이트:</strong> 월 {monthlyExpense}만원의 소비를 아껴 대표 배당성장 ETF에 꾸준히 투자하면, {years}년 후에는 원금({formatMoney(totalSpent)})의 <strong>{(futureAsset / (totalSpent || 1)).toFixed(1)}배인 {formatMoney(futureAsset)}</strong>이 쌓이고, 매달 <strong>{monthlyDividend.toLocaleString()}만원</strong>의 평생 현금흐름이 발생합니다.
          </div>
        </div>
      </div>
    </div>
  );
}
